version: '2.1'

volumes:
  data:
    name: "fullstack-web"

services:

  # pound
  pound:
    image: eeacms/pound:2.7
    ports:
      - "443:80"
    volumes:
      - ${PROJECT_PATH}/config/${ENV}/pound/pound.cfg:/etc/pound/pound.cfg

  # PHP 7.2 Apache
  apache:
    # todo : unstable
    #build: ./docker/config/apache/build
    image: php:${PHP_APACHE_VERSION}
    environment:
      TZ: Europe/Paris
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_PATH}/public:/var/www/html
      - ${PROJECT_PATH}/docker/volume/apache/log:/var/log/apache2
      - ${PROJECT_PATH}/docker/volume/apache/usr/local/etc/php/conf.d/php.ini:/usr/local/etc/php/conf.d/z001.ini

  # Varnish
  varnish:
    image: eeacms/varnish:4.1-6.2
    ports:
      - "80:6081"
      - "6085:6085"
    depends_on:
      - apache
    environment:
      BACKENDS: "${VARNISH_BACKENDS}"
      BACKENDS_PORT: "${VARNISH_BACKENDS_PORT}"
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "${VARNISH_DASHBOARD_USER}"
      DASHBOARD_PASSWORD: "${VARNISH_DASHBOARD_PASSWORD}"
      DASHBOARD_SERVERS: "${VARNISH_DASHBOARD_SERVERS}"
      DASHBOARD_DNS_ENABLED: "true"
    volumes:
      - ${PROJECT_PATH}/docker/volume/${ENV}/varnish/conf.d/varnish.vcl:/etc/varnish/conf.d/default.vcl

  # Mysql server
  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ${PROJECT_PATH}/docker/volume/${ENV}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  # PHPMyadmin (for mysql)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ${PROJECT_PATH}/docker/config/${ENV}/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
    ports:
      - "8181:80"
    links:
      - mysql:mysql

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    volumes:
      - ${PROJECT_PATH}/docker/volume/${ENV}/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"

  # Kibana
  kibana:
    image: kibana:${KIBANA_VERSION}
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch

  # RabbitMQ
  rabbitmq:
    # todo : unstable
    #build: ./docker/config/rabbitmq/build
    image: rabbitmq:${RABBITMQ_VERSION}
    ports:
      - "5672:5672"
      - "15672:15672"
